apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemonset-volume-cm
spec:
  selector:
    matchLabels:
      name: daemonset
  template:
    metadata:
      labels:
        name: daemonset
    spec:
      containers:
      - name: nginx
        image: nginx
      volumes:
      - name: cm 
        configMap:
          name: example
