apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemonset-env-secret
spec:
  selector:
    matchLabels:
      name: daemonset
  template:
    metadata:
      labels:
        name: daemonset
    spec:
      containers:
      - name: nginx
        image: nginx
        env:
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: example
              key: example
