apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-volume-cm
  labels:
    app: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: IfNotPresent
      volumes:
      - name: cm 
        configMap:
          name: example

