apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-env-secret
  labels:
    app: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: IfNotPresent
        env:
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: example
              key: example
