apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-volume-secret
spec:
  selector:
    matchLabels:
      app: nginx 
  serviceName: "statefulset-volume-secret"
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx 
    spec:
      containers:
      - name: nginx
        image: nginx
      volumes:
      - name: secret
        secret:
          secretName: example
