apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-env-cm
spec:
  selector:
    matchLabels:
      app: nginx 
  serviceName: "statefulset-env-cm"
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx 
    spec:
      containers:
      - name: nginx
        image: nginx
        env:
        - name: CM 
          valueFrom:
            configMapKeyRef:
              name: example
              key: example
