apiVersion: apps/v1
kind: Deployment
metadata:
  name: configsyncop
  namespace: configsyncop
  labels:
    app: configsyncop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: configsyncop
  template:
    metadata:
      labels:
        app: configsyncop
    spec:
      serviceAccountName: configsyncop
      containers:
      - name: configsyncop
        image: configsyncop/configsyncop:latest
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - configsyncop
              topologyKey: "kubernetes.io/hostname"

