apiVersion: v1
kind: Namespace
metadata:
  name: configsyncop
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: configsyncop
  namespace: configsyncop
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: configsyncop
  namespace: configsyncop
rules:
# required by kopf
- apiGroups: 
  - zalando.org
  resources: 
  - clusterkopfpeerings
  verbs: 
  - list
  - watch
  - patch
  - get
- apiGroups: 
  - apiextensions.k8s.io
  resources: 
  - customresourcedefinitions
  verbs: 
  - list
  - get
- apiGroups:
  - ""
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
# for app
- apiGroups:
  - apps
  - extensions
  resources:
  - deployments
  - daemonsets
  - statefulsets 
  verbs:
  - list
  - get
  - patch 
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - watch
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: configsyncop
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: configsyncop
subjects:
- kind: ServiceAccount
  name: configsyncop
  namespace: configsyncop

