apiVersion: v1
kind: Namespace
metadata:
  name: configsyncop
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: configsyncop
  namespace: configsyncop
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: configsyncop
  namespace: configsyncop
rules:
- apiGroups:
  - ""
  resources:
  - deployments
  - replicasets
  - daemonsets
  verbs:
  - list
  - update
- apiGroups:
  - ""
  resources:
  - deployments
  - replicasets
  - daemonsets
  verbs:
  - list
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: configsyncop
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: configsyncop
subjects:
- kind: ServiceAccount
  name: configsyncop
  namespace: configsyncop

