{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "configsyncop.fullname" . }}
rules:
# required by kopf
- apiGroups: 
  - zalando.org
  resources: 
  - clusterkopfpeerings
  verbs: 
  - list
  - watch
  - patch
  - get
- apiGroups: 
  - apiextensions.k8s.io
  resources: 
  - customresourcedefinitions
  verbs: 
  - list
  - get
- apiGroups:
  - ""
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
# for app
- apiGroups:
  - apps
  - extensions
  resources:
  - deployments
  - daemonsets
  - statefulsets 
  verbs:
  - list
  - get
  - patch 
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - watch
  - patch
{{- end -}}
